In [104]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [105]:
#Data

#Train data
#specimens 4, 6, 7, 13, 17, 21 at spetrum 908.1
trainData = np.array([0.06710815, 0.06052136, 0.12795535, 0.35012695, 0.46378904, 0.34955011]).reshape((-1, 1))
trainResponses = np.array([1, 1, 1, 0, 0, 0]) #1 = counterfeit, 0 = authentic

#Test data
#specimens 35, 37, 38, 39, 34 at spetrum 908.1
testData = np.array([0.14709364, 0.35198722, 0.32029153, 0.38181356, 0.00390504]).reshape((-1, 1))
testResponses = np.array([1, 0, 0, 0, 1]) #1 = counterfeit, 0 = authentic
IDSpecimens = np.array([35, 37, 38, 39, 34]) 

In [118]:
trainData

array([[0.06710815],
       [0.06052136],
       [0.12795535],
       [0.35012695],
       [0.46378904],
       [0.34955011]])

In [117]:
trainResponses

array([1, 1, 1, 0, 0, 0])

In [108]:
model = LinearRegression()

In [109]:
model.fit(trainData, trainResponses)

LinearRegression()

In [110]:
r_sq = model.score(trainData, trainResponses)
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.9232436647161987


In [111]:
print(f"intercept: {model.intercept_}")
print(f"slope: {model.coef_}")

intercept: 1.2215314905776882
slope: [-3.05076355]


In [112]:
new_model = LinearRegression().fit(trainData, trainResponses.reshape((-1, 1)))
print(f"intercept: {new_model.intercept_}")


print(f"slope: {new_model.coef_}")

intercept: [1.22153149]
slope: [[-3.05076355]]


In [113]:
# Prediction with train data
y_pred = model.predict(trainData)
print(f"predicted response:\n{y_pred}")

predicted response:
[ 1.01680039  1.03689513  0.83116997  0.15337695 -0.19337921  0.15513676]


In [119]:
# Prediction with test data
y_predictions = model.predict(testData)
print(f"predicted response:\n{y_pred}")

predicted response:
[0.77278358 0.14770171 0.24439777 0.0567086  1.20961814]


In [120]:
i = j = 0
for p in y_predictions:
    if p < 0.5 :
        if testResponses[i] < 0.5 : 
            j += 1
        print("specimen " + str(IDSpecimens[i]) + " is a counterfeit")
    else :
        if testResponses[i] >= 0.5 : 
            j += 1
        print("specimen " + str(IDSpecimens[i]) + " is an authentic")
    i += 1

specimen 35 is an authentic
specimen 37 is a counterfeit
specimen 38 is a counterfeit
specimen 39 is a counterfeit
specimen 34 is an authentic


In [121]:
print("test accuracy : " + str(j/len(responses)))


test accuracy : 1.0
